services:
  racestack:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        - USERNAME=${USER}
        - UID=${UID}
        - GID=${GID}
    image: asuf1tenth_racestack_ros2:jazzy
