<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>asuf1tenth_vehicle_interface</name>
  <version>1.2.0</version>
  <description>
    ROS 2 device driver and vehicle interface for ESP32 and FESC on ASU F1TENTH.
  </description>
  <maintainer email="mohany@asu.edu">Mohanad Youssef</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>vesc_msgs</depend>
  <exec_depend>vesc_driver</exec_depend>
  <exec_depend>python3-serial</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
